name: Run Google Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        simd: [NONE, AVX128, AVX256, AVX512]

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtest-dev cmake build-essential libtbb-dev

      - name: Configure
        run: cd ${{ github.workspace }}/cpp && cmake -S . -B build -DSIMD_MODE=${{ matrix.simd }}

      - name: Build
        run: cmake --build cpp/build

      - name: Run Tests
        run: cd ${{ github.workspace }}/cpp/build && ctest -VV
